import type { Metadata } from "next";
import Link from "next/link";

import { PageHeader } from "@/components/PageHeader";
import { SectionHeader } from "@/components/SectionHeader";
import { CONTACT_EMAIL, POLICY_UPDATED } from "@/lib/site";

export const metadata: Metadata = { title: "Terms of use", description: "The rules for using HangingAi." };

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl space-y-8 leading-relaxed">
      <PageHeader kicker={`Last updated ${POLICY_UPDATED}`} title="Terms of use">
        By using HangingAi you agree to these terms. They&apos;re short on purpose.
      </PageHeader>

      <section className="space-y-3">
        <SectionHeader number={1} title="What HangingAi is" />
        <p>
          A free site that collects AI news, papers, models and open-source tools from public sources
          and links to the originals, plus community features: chat rooms, votes, the daily brief and
          the Arena. Third-party content belongs to its owners; we show headlines, short summaries,
          previews and official embeds, and link back.
        </p>
      </section>

      <section className="space-y-3">
        <SectionHeader number={2} title="Your posts" />
        <ul className="list-[square] space-y-2 pl-5 marker:text-tomato">
          <li>You keep ownership of what you post. You let us display, store and moderate it on HangingAi.</li>
          <li>
            Follow the{" "}
            <Link href="/about#community" className="font-semibold underline">
              community rules
            </Link>
            : no harassment, hate, spam, illegal content, or content that isn&apos;t safe for work.
          </li>
          <li>
            We may hide or remove content and suspend accounts that break the rules. Reported comments
            are hidden until a moderator reviews them.
          </li>
          <li>Don&apos;t try to get around rate limits, quotas or moderation, or attack the service.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <SectionHeader number={3} title="AI answers" />
        <p>
          Arena answers are generated by third-party AI models and can be wrong, outdated or
          offensive. They aren&apos;t advice and don&apos;t reflect HangingAi&apos;s views. Check anything
          important before relying on it. Don&apos;t submit personal or confidential information.
        </p>
      </section>

      <section className="space-y-3">
        <SectionHeader number={4} title="Takedowns & copyright" />
        <p>
          If something on HangingAi infringes your rights (a post, a preview image, a demo), email{" "}
          <a className="font-semibold underline" href={`mailto:${CONTACT_EMAIL}`}>
            {CONTACT_EMAIL}
          </a>{" "}
          with the page link, what the content is, and why. We act promptly on valid requests.
          Publishers can also block our crawler; see{" "}
          <Link href="/about#crawler" className="font-semibold underline">
            our crawler
          </Link>
          .
        </p>
      </section>

      <section className="space-y-3">
        <SectionHeader number={5} title="No warranty" />
        <p>
          HangingAi is provided as is, without warranties. To the extent the law allows, we&apos;re not
          liable for indirect or consequential damages from using it. We may change or stop features,
          and update these terms; continued use means you accept the current version.
        </p>
      </section>
    </article>
  );
}
